### ISSUE TITLE
Import-time error: undefined symbol: cudaPeekAtLastError

### ISSUE THREAD

**Issue by jantman** [danielgatis/darknetpy#28]
I'm on Debian Buster (10.6) with Python 3.7.3 and nvidia-cuda-dev 9.2.148-7 installed from debian non-free.

I've finally been able to compile and install with GPU support (``GPU=1 pip3 install darknetpy``) after digging through a number of other issues on here, mainly removing the Debian Rust packages, installing rustup via the shell script installer, and then ``rustup default nightly``.

The package compiles and installs via pip without error. However:

```
# python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from darknetpy.detector import Detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/darknetpy/__init__.py", line 1, in <module>
    from .darknetpy import *
ImportError: /usr/local/lib/python3.7/dist-packages/darknetpy/darknetpy.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaPeekAtLastError
>>>
```

I'm unable to find any solution to this. Current darknet master itself compiles fine on my system, and runs fine using the ``./darknet`` demo script.

Any advice would be greatly appreciated...

**Comment by sklett-src** [comment]
+1 Same Problem, were you able to solve it? somehow a normal shell finds cuda at the right place, but python doesnt.
